CREATE TABLE IF NOT EXISTS tblAPLNews (
  `NewsId` INT NOT NULL AUTO_INCREMENT,
  `CategoryId` INT NOT NULL,
  `TitleTranslationId` INT NOT NULL,
  `XMLArchitecture` MEDIUMTEXT NOT NULL,
  PRIMARY KEY (`NewsId`),
  UNIQUE INDEX `NewsId_UNIQUE` (`NewsId` ASC));

ALTER TABLE tblAPLNews
  ADD CONSTRAINT tblAPLNews_tblAPLCategory_FK
FOREIGN KEY (CategoryId)
REFERENCES tblAPLCategory(CategoryId)
  ON DELETE CASCADE
  ON UPDATE CASCADE;

ALTER TABLE tblAPLNews
  ADD CONSTRAINT tblAPLNews_tblDESTileTranslation_FK
FOREIGN KEY (TitleTranslationId)
REFERENCES tblDESTileTranslation(TileTranslationId)
  ON DELETE CASCADE
  ON UPDATE CASCADE;