CREATE TABLE IF NOT EXISTS tblSECUser (
  `UserId` INT NOT NULL AUTO_INCREMENT,
  `Login` VARCHAR(256) NOT NULL,
  `Email` VARCHAR(256),
  `IsActive` TINYINT(1) NOT NULL DEFAULT 0,
  PRIMARY KEY (`UserId`),
  UNIQUE INDEX `Login_UNIQUE` (`Login` ASC));
