CREATE TABLE IF NOT EXISTS tblSECUserRole (
  `UserId` INT NOT NULL,
  `RoleId` INT NOT NULL,
  PRIMARY KEY (`UserId`, `RoleId`));

ALTER TABLE tblSECUserRole
  ADD CONSTRAINT UserRole_UserId_FK
FOREIGN KEY (UserId)
REFERENCES tblSECUser(UserId)
  ON DELETE CASCADE
  ON UPDATE CASCADE;

ALTER TABLE tblSECUserRole
  ADD CONSTRAINT UserRole_RoleId_FK
FOREIGN KEY (RoleId)
REFERENCES tblSECRole(RoleId)
  ON DELETE CASCADE
  ON UPDATE CASCADE;

